### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by Mordano** [duffn/github-release-orb#9]
## Describe Request: Request about the current status of this project | Additional maintainer needed?

I like the idea of this project/orb and plan to use it in my own project to automate the release process.
But I noticed that the latest release is from October 10, 2021 ([v0.2.0](https://github.com/duffn/github-release-orb/releases/tag/v0.2.0).

After this release, every other commit failed in the CircleCi pipeline and got therefore never released. Additionally, after the release of v0.2.0, the only signal of life was 3 commits on August 27, 2022.

**Comment by duffn** [comment]
I'm going to archive this repository. I don't use this any more and don't plan on maintaining it.
